"use client";
import {useState} from "react";
const checks=["Depot arrival & preparation","Locate all pallets/cages before scanning","Correct scanning process","Van loading & organisation","Delm8 setup and effective use","Route planning","Premium/ETA management","Delivery & proof process","Collections","Returns & unattempted procedure","Vehicle checks","Communication & escalation","End-of-day procedure"];
const levels=["Explained","Demonstrated","Practised","Competent"];
export default function Trainer(){
 const [trainer,setTrainer]=useState(""),[trainee,setTrainee]=useState(""),[depot,setDepot]=useState(""),[scores,setScores]=useState({}),[outcome,setOutcome]=useState(""),[solo,setSolo]=useState(""),[notes,setNotes]=useState(""),[status,setStatus]=useState("");
 const complete=trainer.trim()&&trainee.trim()&&depot&&checks.every(c=>scores[c])&&outcome&&solo;
 async function submit(e){e.preventDefault();if(!complete){setStatus("Complete every field and competency before sign-off.");return}
 setStatus("Submitting signed assessment...");
 const r=await fetch("/api/training-signoff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trainer:trainer.trim(),trainee:trainee.trim(),depot,scores,outcome,solo,notes})});
 const data=await r.json().catch(()=>({}));
 setStatus(r.ok?"✓ Assessment signed and submitted.":data.error||"Submission failed. Please try again.");
 }
 return <main className="inner wide"><a href="/">← Home</a><p className="eyebrow">TRAINER HUB</p><h1>Trainee assessment</h1><p className="lead">Complete the practical assessment, record the final outcome and submit the signed training record.</p>
 <form onSubmit={submit}><div className="identity"><label>Trainer name<input value={trainer} onChange={e=>setTrainer(e.target.value)} placeholder="Full name"/></label><label>Trainee name<input value={trainee} onChange={e=>setTrainee(e.target.value)} placeholder="Full name"/></label><label>Depot location<select value={depot} onChange={e=>setDepot(e.target.value)} required><option value="">Select depot</option>{["Rotherham","Leeds","Huntingdon","Luton"].map(d=><option key={d} value={d}>{d}</option>)}</select></label></div>
 <div className="assessment"><div className="assHead"><b>Competency</b>{levels.map(x=><span key={x}>{x}</span>)}</div>{checks.map(c=><div className="assRow" key={c}><b>{c}</b>{levels.map(l=><label className="radio" key={l}><input type="radio" name={c} checked={scores[c]===l} onChange={()=>setScores({...scores,[c]:l})}/><span className="radioDot">●</span><span className="radioLabel">{l}</span></label>)}</div>)}</div>
 <div className="finalBox"><h2>Final assessment</h2><label>Overall result<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">Select result</option><option>GREEN - Independent</option><option>AMBER - Support required</option><option>RED - Further training required</option></select></label><label>Ready for Solo Route?<select value={solo} onChange={e=>setSolo(e.target.value)}><option value="">Select</option><option>YES</option><option>NO</option></select></label><label>Trainer notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Support required, strengths, concerns or follow-up actions..."/></label><p className="declaration">By submitting, the named trainer confirms this assessment reflects the trainee's demonstrated ability at the time of sign-off.</p><button type="submit">Sign Off & Submit</button>{status&&<p className="submitStatus">{status}</p>}</div></form></main>}