"use client";import{useState}from"react";
const issues=[
["Missing parcel","Freight","Call the DX office and ask them to check whether the parcel has been left at the depot","If the parcel is not at the depot, spend up to 5 minutes thoroughly checking the van","If it still cannot be found after the 5-minute search, mark the stop as No Access on the DX scanner","Take the required blank/black proof image by covering the camera against your leg so the image is black","Continue the route and follow any further instruction from the DX office or your lead driver"],
["Missing pallet / cage","Loading","Stop scanning and confirm every pallet/cage allocated to the route","Check the route labels and depot allocation","Ask depot staff to locate missing freight","Do not depart until the allocation has been checked"],
["Cannot find address","Delivery","Check the house number, street, postcode and any property name on the parcel","Use Delm8 to locate and navigate to the next DX-sequenced address","Check PostTag for additional property/location information","Use what3words where available to pinpoint the location","Check Spoke for useful delivery/location information","Google-search the address or business name for additional location clues","Check property numbers/names safely when you arrive","If the address still cannot be confirmed, contact your lead driver or depot before creating an avoidable failed attempt"],
["Customer unavailable","Delivery","Confirm you are at the correct property","Follow the approved DX delivery options shown for the consignment","Take the required clear POD evidence for any completed delivery","Use the correct scan outcome","Do not invent a recipient or delivery outcome"],
["Premium at risk","Premiums","Check the premium window immediately","Continue to follow the DX scanner sequence while assessing the risk","Contact your lead driver/manager early","Follow the instruction given to protect service","Do not wait until the window has failed"],
["Running late","ETAs","Check remaining DX sequence and timed work","Identify the cause and likely impact","Tell your lead driver before service is affected","Continue safely and follow any support instruction","Never rush, speed or drive unsafely to recover time"],
["Collection at risk","Collections","Check the collection time requirement","Assess your position in the DX sequence","Contact your lead driver/manager immediately","Follow any support or route instruction given","Do not allow a collection to fail through lack of communication"],
["Unable to attempt","Returns","Check the address and all reasonable approved options","Do not mark freight unattempted without authority","Contact your lead driver or manager","Record the correct DX outcome","Return freight only through the correct depot process"],
["Scanner issue","Technology","Keep the freight secure","Restart/check the DX scanner where appropriate","Tell your lead driver/depot that the scanner is affecting service","Follow depot instruction for continuing work","Do not create false scans or outcomes"],
["Delm8 issue","Technology","Remember the DX scanner controls delivery sequence","Check the address/postcode directly from the DX job","Restart or re-enter the location in Delm8","Use an approved alternative navigation method if required","Do not reorder the DX route because navigation is unavailable"],
["Vehicle defect","Vehicle","Stop and assess whether the defect affects safety","Report the defect immediately","Do not continue with a safety-critical defect","Follow manager/depot instruction for vehicle recovery or replacement","Record/report the defect through the required process"],
["Fuel / AdBlue warning","Vehicle","Check the warning and remaining level","Plan a safe refuel/top-up before it threatens route completion","Tell your lead driver if service could be affected","Do not ignore warning lights or abnormal consumption"],
["Breakdown","Vehicle","Get the vehicle to a safe position where possible","Use hazards and keep yourself safe","Contact your lead driver/manager immediately","Follow breakdown/recovery instructions","Keep freight secure and report any service risk"],
["Road traffic / vehicle incident","Safety","Stop safely and deal with any immediate danger","Record exact location, date and time","Record EasyDrop vehicle registration and driver name","Collect third-party contact, registration and insurance details where available","Take clear photos and videos of all damage from multiple angles","Record a 360° video of the area and possible CCTV locations","Record witnesses/dashcam information and a clear description","Contact your OSM before leaving when safe and report within 24 hours"],["End-of-day discrepancy","End of Day","Stop and reconcile deliveries, collections and remaining freight","Check scanner outcomes against freight physically present","Tell depot/lead driver about any discrepancy","Complete returns and paperwork correctly","Do not leave an unexplained discrepancy for the next day"]
];
const depots=[["Rotherham","07971 468778","07971468778"],["Leeds","07779 262099","07779262099"]];const postTag=["https://play.google.com/store/apps/details?id=uk.co.posttagpro","https://apps.apple.com/gb/app/posttag-for-the-drivers/id1396801367"];
export default function Guide(){const[q,setQ]=useState(""),[active,setActive]=useState(null);const filtered=issues.filter(x=>x.join(" ").toLowerCase().includes(q.toLowerCase()));if(active){const x=active;return <main className="inner wide issuePage"><button className="guideBack" onClick={()=>setActive(null)}>‹ All Driver Issues</button><p className="eyebrow">{x[1].toUpperCase()}</p><h1>{x[0]}</h1><p className="lead">Follow these steps in order. Escalate early if the issue cannot be resolved correctly.</p><div className="issueProcess"><h2><span>!</span> What to do</h2>{x.slice(2).map((step,i)=><div className="issueStep" key={step}><i>{i+1}</i><b>{step}</b></div>)}</div><section className="addressTool"><small>ADDRESS FINDER</small><h2>PostTag</h2><p>Need extra help finding the property? Download PostTag and use it as an additional address and location-checking tool.</p><div className="postTagButtons"><a href="https://play.google.com/store/apps/details?id=uk.co.posttagpro" target="_blank" rel="noreferrer"><span className="storeBadge"><span className="googlePlayMark"><i></i><i></i><i></i><i></i></span><span>Google Play</span></span></a><a href="https://apps.apple.com/gb/app/posttag-for-the-drivers/id1396801367" target="_blank" rel="noreferrer"><span className="storeBadge"><span className="appleSimple" aria-hidden="true">●</span><span>App Store</span></span></a></div><div className="royalMailFinder"><small>OFFICIAL ADDRESS CHECK</small><h3>Royal Mail Postcode &amp; Address Finder</h3><p>Use Royal Mail to check the postcode or confirm the correct address.</p><a className="rmOpen" href="https://www.royalmail.com/rml-shared-find-a-postcode" target="_blank" rel="noreferrer">Open Royal Mail Address Finder ↗</a></div></section><div className="depotHelp"><h3>Need DX depot assistance?</h3><div className="depotCallGrid">{depots.map(([name,display,tel])=><a href={"tel:"+tel} key={name}><div><small>DX OFFICE</small><b>{name}</b><span>{display}</span></div><strong>☎ CALL</strong></a>)}</div></div><div className="issueReminder"><b>KEY STANDARD</b><p>Protect the customer, the freight and the service. Use the correct DX process and communicate while the problem can still be solved.</p></div></main>}return <main className="inner wide"><a href="/">← Home</a><p className="eyebrow">DRIVER GUIDE</p><h1>Something gone wrong?</h1><p className="lead">Find the issue and follow the steps. Built for quick answers while you're on route.</p><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search: missing parcel, premium, scanner, breakdown..."/><div className="issueGrid">{filtered.map(x=><button type="button" key={x[0]} onClick={()=>setActive(x)}><small>{x[1]}</small><b>{x[0]}</b><span>›</span></button>)}</div></main>}