"use client";import{useState}from"react";
const modules=[
["01","Getting Started",["Arrive ready and on time","Know your route allocation","Check messages and depot instructions","Raise questions before leaving depot"]],
["02","Morning & Loading",["Locate every pallet and cage allocated to your route before scanning","Confirm all freight is accounted for","Scan freight using the correct process","Load the van in a delivery-friendly sequence","Recheck missing or unexpected freight before departure"]],
["03","Delm8 & Route Planning",["Load or enter your stops into Delm8","Identify premiums and timed work first","Review the suggested route before leaving","Adjust the sequence when real-world conditions require it","Keep Delm8 updated as the route progresses"]],
["04","Premiums & ETAs",["Identify every premium before departure","Plan the route around the premium window","Monitor ETAs throughout the day","Re-plan immediately when delays put a premium at risk","Escalate early, never after the window has already failed"]],
["05","Normal Delivery",["Confirm the correct address and property","Approach the door with the correct parcel","Where the customer answers, complete the handover at the open doorway","Take clear proof showing the parcel at the attended property","Complete the correct delivery scan before moving on"]],
["06","Premium Delivery",["Confirm you are at the correct address","Confirm the recipient's name","Hand the parcel directly into the customer's hands","Obtain the customer's signature on the DX system","Complete the signed delivery scan before leaving"]],
["07","Collections",["Identify collections and their time requirements","Build them into the route","Monitor progress so the collection is not forgotten","If timing becomes at risk, communicate immediately","Complete the correct collection scan and account for the freight"]],
["08","Returns & Unattempted",["Do not create unauthorised unattempted freight","Recheck the address, route and available options","Contact your lead driver or manager before returning avoidable freight","Record the correct outcome","Return and account for freight using depot procedure"]],
["09","Vehicle Responsibilities",["Complete the pre-route vehicle check","Check tyres, lights, mirrors and visible damage","Check fuel and AdBlue before departure","Report defects immediately","Do not ignore a safety-critical warning or defect"]],
["10","Communication & End of Day",["Raise service problems while they can still be solved","Use the lead driver as first contact where appropriate","Account for deliveries and collections","Return freight and complete required paperwork","Report unresolved issues and leave the vehicle ready for the next shift"]]
];
export default function Training(){const[open,setOpen]=useState("05");return <main className="inner wide"><a href="/">← Home</a><p className="eyebrow">EASYDROP TRAINING</p><h1>Training Modules</h1><p className="lead">Tap any module for the step-by-step procedure. Use these guides whenever you're unsure.</p><div className="moduleList">{modules.map(([n,t,steps])=><article className={"trainingModule "+(open===n?"open":"")} key={n}><button className="moduleButton" onClick={()=>setOpen(open===n?"":n)}><span>{n}</span><div><h2>{t}</h2><p>Step-by-step EasyDrop procedure</p></div><b>{open===n?"−":"+"}</b></button>{open===n&&<div className="moduleBody"><h3>Step-by-step process</h3><ol>{steps.map((s,i)=><li key={s}><span>{i+1}</span><p>{s}</p></li>)}</ol>{n==="05"&&<div className="perfectExample normal"><div><strong>✓ PERFECT NORMAL DELIVERY</strong><h3>What good looks like</h3></div><ul><li>Correct property</li><li>Door open and customer present</li><li>Parcel clearly shown at the open doorway</li><li>Clear, usable proof of delivery</li><li>Correct delivery scan completed</li></ul></div>}{n==="06"&&<div className="perfectExample premium"><div><strong>★ PERFECT PREMIUM DELIVERY</strong><h3>Signed handover standard</h3></div><ul><li>Parcel handed directly into customer's hands</li><li>Recipient name confirmed</li><li>Customer signature obtained</li><li>Correct address and parcel confirmed</li><li>Signed delivery scan completed</li></ul><p className="warning">Premium freight must not be treated as an unattended doorstep delivery where a signed handover is required.</p></div>}<div className="helpBox"><b>Something gone wrong?</b><p>Stop and escalate early if the correct procedure cannot be completed. Do not wait until the end of the route.</p></div></div>}</article>)}</div><div className="trainingNote"><b>Practical competency</b><p>Learning modules are available to all drivers. Practical competency and Ready for Solo Route status must be recorded by a trainer.</p></div></main>}